token_v2: <your_token>
database_url: <your_notion_database_url>"
hexo_post_path: <your_hexo_post_path>
# https://hexo.io/zh-cn/docs/permalinks 
# 不支持 :id  category 只支持一个 
sulg_format: ':year-:day-:month-:name'

